---
- name: "Install from homebrew"
  homebrew:
    name:
      - pandoc
      - graphviz
      - bcrypt
      - git
      - ssh-copy-id
    state: present

- name : "Tap homebrew versions cask"
  homebrew_tap: caskroom/versions

- name: "Install from homebrew cask"
  homebrew_cask:
    name:
      - firefox-beta
      - dash # Documentations
      - keka # unarchive
      - slack # chat
      - spectacle # window manager
      - vlc # video player
      - numi # calc
      - iterm2
    state: present
